# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'danwkennedy/docker-node'
  flavor: alpine

steps:
- task: Docker@1
  displayName: Build image
  inputs:
    command: build
    dockerFile: Dockerfile
    imageName: $(imageName):$(version)
    arguments: --build-arg NODE_VERSION=$(version)-$(flavor)

- task: Docker@1
  displayName: Tag Image
  inputs:
    command: tag
    imageName: $(imageName):$(version)
    tagMultipleImages: true
    imageNamesPath: ./image-tags.txt

- task: Docker@1
  displayName: Tag Latest
  inputs:
    command: tag
    imageName: $(imageName):$(version)
  condition: $(latest)

- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: DockerHub

- task: Docker@1
  displayName: Push image
  inputs:
    command: push
    imageName: $(imageName):$(version)

