# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'danwkennedy/docker-node'
  flavor: alpine

steps:
- task: Docker@1
  displayName: Build image
  inputs:
    command: build
    dockerFile: Dockerfile
    imageName: $(imageName):$(version)-$(flavor)
    arguments: --build-arg NODE_VERSION=$(version)-$(flavor)

- task: Docker@1
  displayName: Tag version
  inputs:
    command: tag
    imageName: $(imageName):$(version)-$(flavor)
    arguments: $(imageName):$(version)

- task: Docker@1
  displayName: Tag major and flavor
  inputs:
    command: tag
    imageName: $(imageName):$(version)-$(flavor)
    arguments: $(imageName):$(major)-$(flavor)

- task: Docker@1
  displayName: Tag major
  inputs:
    command: tag
    imageName: $(imageName):$(version)-$(flavor)
    arguments: $(imageName):$(major)

- task: Docker@1
  displayName: Tag flavor
  inputs:
    command: tag
    imageName: $(imageName):$(version)-$(flavor)
    arguments: $(imageName):$(flavor)

- task: Docker@1
  displayName: Tag Latest
  inputs:
    command: tag
    imageName: $(imageName):$(version)-$(flavor)
    arguments: $(imageName):latest
  condition: variables.latest

- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: DockerHub

- task: Docker@1
  displayName: Push image
  inputs:
    command: push
    imageName: $(imageName):$(version)

