# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'danwkennedy/docker-node'
  version: 
  tags: latest,alpine,11,$(version)

steps:
- task: Docker@1
  displayName: Build image
  inputs:
    command: build
    dockerFile: Dockerfile
    imageName: $(imageName):$(version)

- task: Docker@1
  displayName: Tag Image
  inputs:
    command: tag
    imageName: $(imageName):latest
    arguments: tags

- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: DockerHub

- task: Docker@1
  displayName: Push image
  inputs:
    command: push
    imageName: $(imageName):$(version)

